/**
 * Generates the per-service C# from a mokkapi Service:
 *   - `Endpoints.cs`  — ServiceInfo + each endpoint/variant as readable C# data
 *   - route registrations — the explicit `app.MapMethods(...)` lines for Program.cs
 *
 * Variant bodies are emitted as C# raw string literals (`"""…"""`) so JSON/XML/HTML
 * stays readable and unescaped; the closing fence sits at column 0 so no indentation
 * is stripped, and the fence length grows past any run of quotes inside the body.
 */

import type { Service, Endpoint, ResponseVariant, MatchRuleValue, JsonPathRule } from '../../../shared/models';

export interface EmittedEndpoints {
  endpointsCs: string;
  routeRegistrations: string;
  warnings: string[];
}

export function emitEndpoints(service: Service): EmittedEndpoints {
  const warnings: string[] = [];
  const usedIdents = new Set<string>();
  const seenRoutes = new Set<string>();

  const fields: string[] = [];
  const routes: string[] = [];

  for (const ep of service.endpoints) {
    const route = routeTemplate(ep.path);
    const routeKey = `${ep.method} ${route}`;
    if (seenRoutes.has(routeKey)) {
      warnings.push(`Skipped duplicate route ${routeKey} (ASP.NET allows one handler per method+path).`);
      continue;
    }
    seenRoutes.add(routeKey);

    const ident = uniqueIdent(ep, usedIdents);
    fields.push(emitEndpointField(ident, ep, route));
    routes.push(
      `app.MapMethods(${csString(route)}, new[] { ${csString(ep.method)} }, ` +
        `(HttpContext ctx) => MockEngine.Handle(ctx, Endpoints.${ident}));`,
    );
  }

  const endpointsCs = renderEndpointsFile(service, fields);
  return {
    endpointsCs,
    routeRegistrations: routes.join('\n'),
    warnings,
  };
}

// ─── File assembly ──────────────────────────────────────────────────────────────

function renderEndpointsFile(service: Service, fields: string[]): string {
  const origins = service.cors?.allowedOrigins ?? ['*'];
  const originsLiteral = origins.length > 0 ? `{ ${origins.map(csString).join(', ')} }` : '{ }';

  return `// Generated by mokkapi — do not edit by hand (re-export from the app instead).
namespace MokkapiMock;

public static class ServiceInfo
{
    public const string Id = ${csString(service.id)};
    public const string Name = ${csString(service.name)};
    public const int Port = ${service.port};
    public const string DefaultScenario = ${csString(service.activeScenario)};
    public static readonly string[] AllowedOrigins = ${originsLiteral};
}

public static class Endpoints
{
${fields.join('\n\n')}
}
`;
}

function emitEndpointField(ident: string, ep: Endpoint, route: string): string {
  // NOTE: variant blocks are kept at column 0 (not re-indented) because each ends
  // with a raw-string body whose closing fence must sit at column 0 — re-indenting
  // would change the literal's stripped indentation and fail to compile.
  const variants = ep.variants.map(emitVariant).join(',\n');
  return [
    `    // ${ep.method} ${route}`,
    `    public static readonly EndpointDef ${ident} = new()`,
    `    {`,
    `        Method = ${csString(ep.method)},`,
    `        Path = ${csString(ep.path)},`,
    `        Description = ${csString(ep.description ?? '')},`,
    `        ForcedVariantId = ${ep.forcedVariantId ? csString(ep.forcedVariantId) : 'null'},`,
    `        Variants = new()`,
    `        {`,
    variants,
    `        },`,
    `    };`,
  ].join('\n');
}

function emitVariant(v: ResponseVariant): string {
  const scenarios = v.scenarios.length > 0
    ? `new() { ${v.scenarios.map(csString).join(', ')} }`
    : 'new()';
  const headers = emitStringDict(v.headers);

  // Body is emitted LAST so the raw-string literal (which must sit at column 0)
  // is followed only by the closing brace.
  const head = [
    `new VariantDef`,
    `{`,
    `    Id = ${csString(v.id)},`,
    `    Name = ${csString(v.name)},`,
    `    Scenarios = ${scenarios},`,
    `    Match = ${emitMatch(v.match)},`,
    `    DelayMs = ${Math.max(0, Math.trunc(v.delayMs))},`,
    `    Status = ${v.status},`,
    `    Headers = ${headers},`,
    `    BodyKind = ${csString(v.bodyKind)},`,
    `    Body =`,
  ].join('\n');

  // The raw body block is intentionally not indented.
  return `${head}\n${csBody(v.body ?? '')}\n}`;
}

function emitMatch(match: ResponseVariant['match']): string {
  const headers = emitRuleDict(match.headers);
  const query = emitRuleDict(match.query);
  const jsonPath = match.bodyJsonPath.length > 0
    ? `new() { ${match.bodyJsonPath.map(emitJsonPathRule).join(', ')} }`
    : 'new()';
  return `new MatchDef { Headers = ${headers}, Query = ${query}, BodyJsonPath = ${jsonPath} }`;
}

function emitRuleDict(rules: Record<string, MatchRuleValue>): string {
  const entries = Object.entries(rules);
  if (entries.length === 0) return 'new()';
  const body = entries
    .map(([k, v]) => `[${csString(k)}] = ${emitRuleVal(v)}`)
    .join(', ');
  return `new() { ${body} }`;
}

function emitRuleVal(rule: MatchRuleValue): string {
  if (typeof rule === 'object' && rule !== null && 'regex' in rule) {
    return `new RuleVal { IsRegex = true, Value = ${csString(rule.regex)} }`;
  }
  return `new RuleVal { IsRegex = false, Value = ${csString(String(rule))} }`;
}

function emitJsonPathRule(rule: JsonPathRule): string {
  return `new JsonPathRule { Path = ${csString(rule.path)}, Op = ${csString(rule.op)}, Value = ${emitJsonPathValue(rule.value)} }`;
}

function emitJsonPathValue(value: JsonPathRule['value']): string {
  if (value === undefined || value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return `${value}d`; // double, to match StrictEquals/gt/lt
  return csString(String(value));
}

function emitStringDict(dict: Record<string, string>): string {
  const entries = Object.entries(dict);
  if (entries.length === 0) return 'new()';
  const body = entries.map(([k, v]) => `[${csString(k)}] = ${csString(v)}`).join(', ');
  return `new() { ${body} }`;
}

// ─── C# literal helpers ─────────────────────────────────────────────────────────

function csString(s: string): string {
  const escaped = s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

/** C# raw string literal for a body; fences at column 0, length > any quote run. */
function csBody(body: string): string {
  if (body === '') return '""';
  const longestQuoteRun = (body.match(/"+/g) ?? []).reduce((max, run) => Math.max(max, run.length), 0);
  const fence = '"'.repeat(Math.max(3, longestQuoteRun + 1));
  return `${fence}\n${body}\n${fence}`;
}

function routeTemplate(path: string): string {
  return path.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function uniqueIdent(ep: Endpoint, used: Set<string>): string {
  const base = sanitizeIdent(`${ep.method}_${ep.path}`);
  let ident = base;
  let n = 2;
  while (used.has(ident)) ident = `${base}_${n++}`;
  used.add(ident);
  return ident;
}

function sanitizeIdent(raw: string): string {
  let s = raw
    .replace(/:/g, '')          // drop param markers
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (s === '' || /^[0-9]/.test(s)) s = `Ep_${s}`;
  // PascalCase the first letter for a conventional field name
  return s.charAt(0).toUpperCase() + s.slice(1);
}
